### ISSUE TITLE
Registering with Long Inputs username display webpage

### ISSUE THREAD

**Issue by AnjeloTing** [antonstaana/STSWENG-S13-Git#3]
![1](https://user-images.githubusercontent.com/49316736/104551649-3deaf180-5672-11eb-9b19-8d43c3201142.jpg)
Steps to Reproduce:
Go to main page
Click Login
Register an account with these inputs 
Email: abcd4321@gmail.com
First name: Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Last name: Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbb
Password: asd4321
Confirm Password: asdf4321 
Number: 09123654987
All optional inputs blank
Register the account

Description: The name is too long that it widens the webpage display.

Suggestion: Limit the Name input so that this won't happen.

**Comment by antonstaana** [comment]
Fixed: Added and adjusted textbreak and overflow settings. Also limited text input to all relevant fields to 255. overfill.png
![limits](https://user-images.githubusercontent.com/54714576/104641935-5811e780-56e5-11eb-844e-ebb096a8b5a3.png)
