### ISSUE TITLE
Registering restaurant category not informative

### ISSUE THREAD

**Issue by AnjeloTing** [antonstaana/STSWENG-S13-Git#4]
![2](https://user-images.githubusercontent.com/49316736/104554887-db94ef80-5677-11eb-81e8-c1946ccdf399.jpg)
Description: As a user I do not know what to input here.
Suggestion: Instead of a text input, place a drop down category to which they can pick from.

**Comment by antonstaana** [comment]
Fixed: Changed categories input from textboxt to datalist, with preset categories based off the following article: https://www.webstaurantstore.com/article/353/types-of-restaurants.html categories.png
![categories](https://user-images.githubusercontent.com/54714576/104641790-3153b100-56e5-11eb-8322-f507459ce1db.png)
