### ISSUE TITLE
Page hang when input 10,000 character for login

### ISSUE THREAD

**Issue by AnjeloTing** [antonstaana/STSWENG-S13-Git#5]
![3](https://user-images.githubusercontent.com/49316736/104561441-5f53d980-5682-11eb-8918-7ecd2200ef5e.jpg)
Steps to Reproduce:
Go to Main menu page
Login
Username: Letter a 10,000
Password: Letter a 10,000

Result: The page hanged after clicking the login button and turned into the photo shown above

**Comment by antonstaana** [comment]
Fixed: Limited all relevant inputs to a maximum of 255 characters 
![limits](https://user-images.githubusercontent.com/54714576/104641694-13864c00-56e5-11eb-99d5-3714484e97cb.png)
